[package]
name = "stegtools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
bitvec = "1.0.1"
image = "0.25.4"
itertools = "0.13.0"
plotters = "0.3.7"
serde = "1.0.214"
serde_json = "1.0.132"
